# Generated by Django 5.1.3 on 2024-11-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mileage',
            field=models.DecimalField(decimal_places=2, default=10000000, max_digits=12),
        ),
    ]
