--
-- PostgreSQL database dump
--

-- Dumped from database version 14.13 (Homebrew)
-- Dumped by pg_dump version 14.13 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_userprofile; Type: TABLE; Schema: public; Owner: ecommerce_user
--

CREATE TABLE public.accounts_userprofile (
    id bigint NOT NULL,
    gender character varying(1) NOT NULL,
    age_group character varying(2) NOT NULL,
    income_level character varying(1) NOT NULL,
    dummy_field boolean NOT NULL,
    user_id integer NOT NULL,
    mileage numeric(12,2) NOT NULL
);


ALTER TABLE public.accounts_userprofile OWNER TO ecommerce_user;

--
-- Name: accounts_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce_user
--

ALTER TABLE public.accounts_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_userprofile_preferred_categories; Type: TABLE; Schema: public; Owner: ecommerce_user
--

CREATE TABLE public.accounts_userprofile_preferred_categories (
    id bigint NOT NULL,
    userprofile_id bigint NOT NULL,
    productcategory_id bigint NOT NULL
);


ALTER TABLE public.accounts_userprofile_preferred_categories OWNER TO ecommerce_user;

--
-- Name: accounts_userprofile_preferred_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce_user
--

ALTER TABLE public.accounts_userprofile_preferred_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_userprofile_preferred_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: ecommerce_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO ecommerce_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: ecommerce_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO ecommerce_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: ecommerce_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO ecommerce_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: ecommerce_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO ecommerce_user;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: ecommerce_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO ecommerce_user;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: ecommerce_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO ecommerce_user;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: ecommerce_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO ecommerce_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: ecommerce_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO ecommerce_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: ecommerce_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO ecommerce_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: ecommerce_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO ecommerce_user;

--
-- Name: products_cartitem; Type: TABLE; Schema: public; Owner: ecommerce_user
--

CREATE TABLE public.products_cartitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    added_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.products_cartitem OWNER TO ecommerce_user;

--
-- Name: products_cartitem_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce_user
--

ALTER TABLE public.products_cartitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_cartitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_product; Type: TABLE; Schema: public; Owner: ecommerce_user
--

CREATE TABLE public.products_product (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    price numeric(10,2) NOT NULL,
    image character varying(100) NOT NULL,
    theme character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    average_rating double precision NOT NULL,
    stock integer NOT NULL,
    total_views integer NOT NULL,
    category_id bigint
);


ALTER TABLE public.products_product OWNER TO ecommerce_user;

--
-- Name: products_product_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce_user
--

ALTER TABLE public.products_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_productcategory; Type: TABLE; Schema: public; Owner: ecommerce_user
--

CREATE TABLE public.products_productcategory (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.products_productcategory OWNER TO ecommerce_user;

--
-- Name: products_productcategory_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce_user
--

ALTER TABLE public.products_productcategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_productcategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_productfavorite; Type: TABLE; Schema: public; Owner: ecommerce_user
--

CREATE TABLE public.products_productfavorite (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.products_productfavorite OWNER TO ecommerce_user;

--
-- Name: products_productfavorite_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce_user
--

ALTER TABLE public.products_productfavorite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_productfavorite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_productreview; Type: TABLE; Schema: public; Owner: ecommerce_user
--

CREATE TABLE public.products_productreview (
    id bigint NOT NULL,
    rating integer NOT NULL,
    comment text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.products_productreview OWNER TO ecommerce_user;

--
-- Name: products_productreview_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce_user
--

ALTER TABLE public.products_productreview ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_productreview_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_productview; Type: TABLE; Schema: public; Owner: ecommerce_user
--

CREATE TABLE public.products_productview (
    id bigint NOT NULL,
    view_duration integer NOT NULL,
    viewed_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.products_productview OWNER TO ecommerce_user;

--
-- Name: products_productview_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce_user
--

ALTER TABLE public.products_productview ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_productview_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_recommendationlog; Type: TABLE; Schema: public; Owner: ecommerce_user
--

CREATE TABLE public.products_recommendationlog (
    id bigint NOT NULL,
    score double precision NOT NULL,
    recommended_at timestamp with time zone NOT NULL,
    clicked boolean NOT NULL,
    purchased boolean NOT NULL,
    product_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.products_recommendationlog OWNER TO ecommerce_user;

--
-- Name: products_recommendationlog_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce_user
--

ALTER TABLE public.products_recommendationlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_recommendationlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_userbehavior; Type: TABLE; Schema: public; Owner: ecommerce_user
--

CREATE TABLE public.products_userbehavior (
    id bigint NOT NULL,
    view_duration double precision NOT NULL,
    click_count integer NOT NULL,
    last_viewed timestamp with time zone NOT NULL,
    cart_add_count integer NOT NULL,
    purchase_count integer NOT NULL,
    product_id bigint NOT NULL,
    user_id integer NOT NULL,
    favorite_count integer NOT NULL,
    review_score double precision NOT NULL
);


ALTER TABLE public.products_userbehavior OWNER TO ecommerce_user;

--
-- Name: products_userbehavior_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce_user
--

ALTER TABLE public.products_userbehavior ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_userbehavior_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_userproductrating; Type: TABLE; Schema: public; Owner: ecommerce_user
--

CREATE TABLE public.products_userproductrating (
    id bigint NOT NULL,
    rating integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id integer NOT NULL,
    content text NOT NULL
);


ALTER TABLE public.products_userproductrating OWNER TO ecommerce_user;

--
-- Name: products_userproductrating_id_seq; Type: SEQUENCE; Schema: public; Owner: ecommerce_user
--

ALTER TABLE public.products_userproductrating ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_userproductrating_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_userprofile accounts_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_pkey PRIMARY KEY (id);


--
-- Name: accounts_userprofile_preferred_categories accounts_userprofile_pre_userprofile_id_productca_cf6412db_uniq; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.accounts_userprofile_preferred_categories
    ADD CONSTRAINT accounts_userprofile_pre_userprofile_id_productca_cf6412db_uniq UNIQUE (userprofile_id, productcategory_id);


--
-- Name: accounts_userprofile_preferred_categories accounts_userprofile_preferred_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.accounts_userprofile_preferred_categories
    ADD CONSTRAINT accounts_userprofile_preferred_categories_pkey PRIMARY KEY (id);


--
-- Name: accounts_userprofile accounts_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: products_cartitem products_cartitem_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_cartitem
    ADD CONSTRAINT products_cartitem_pkey PRIMARY KEY (id);


--
-- Name: products_cartitem products_cartitem_user_id_product_id_de751152_uniq; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_cartitem
    ADD CONSTRAINT products_cartitem_user_id_product_id_de751152_uniq UNIQUE (user_id, product_id);


--
-- Name: products_product products_product_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_pkey PRIMARY KEY (id);


--
-- Name: products_productcategory products_productcategory_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_productcategory
    ADD CONSTRAINT products_productcategory_pkey PRIMARY KEY (id);


--
-- Name: products_productfavorite products_productfavorite_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_productfavorite
    ADD CONSTRAINT products_productfavorite_pkey PRIMARY KEY (id);


--
-- Name: products_productfavorite products_productfavorite_user_id_product_id_671c3413_uniq; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_productfavorite
    ADD CONSTRAINT products_productfavorite_user_id_product_id_671c3413_uniq UNIQUE (user_id, product_id);


--
-- Name: products_productreview products_productreview_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_productreview
    ADD CONSTRAINT products_productreview_pkey PRIMARY KEY (id);


--
-- Name: products_productreview products_productreview_user_id_product_id_f7f3afc0_uniq; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_productreview
    ADD CONSTRAINT products_productreview_user_id_product_id_f7f3afc0_uniq UNIQUE (user_id, product_id);


--
-- Name: products_productview products_productview_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_productview
    ADD CONSTRAINT products_productview_pkey PRIMARY KEY (id);


--
-- Name: products_recommendationlog products_recommendationlog_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_recommendationlog
    ADD CONSTRAINT products_recommendationlog_pkey PRIMARY KEY (id);


--
-- Name: products_userbehavior products_userbehavior_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_userbehavior
    ADD CONSTRAINT products_userbehavior_pkey PRIMARY KEY (id);


--
-- Name: products_userbehavior products_userbehavior_user_id_product_id_637ebeb4_uniq; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_userbehavior
    ADD CONSTRAINT products_userbehavior_user_id_product_id_637ebeb4_uniq UNIQUE (user_id, product_id);


--
-- Name: products_userproductrating products_userproductrating_pkey; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_userproductrating
    ADD CONSTRAINT products_userproductrating_pkey PRIMARY KEY (id);


--
-- Name: products_userproductrating products_userproductrating_user_id_product_id_5bb5df20_uniq; Type: CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_userproductrating
    ADD CONSTRAINT products_userproductrating_user_id_product_id_5bb5df20_uniq UNIQUE (user_id, product_id);


--
-- Name: accounts_userprofile_prefe_productcategory_id_b2d7e7fa; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX accounts_userprofile_prefe_productcategory_id_b2d7e7fa ON public.accounts_userprofile_preferred_categories USING btree (productcategory_id);


--
-- Name: accounts_userprofile_prefe_userprofile_id_4f6c1827; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX accounts_userprofile_prefe_userprofile_id_4f6c1827 ON public.accounts_userprofile_preferred_categories USING btree (userprofile_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: products_cartitem_product_id_e735c06a; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX products_cartitem_product_id_e735c06a ON public.products_cartitem USING btree (product_id);


--
-- Name: products_cartitem_user_id_c496ef06; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX products_cartitem_user_id_c496ef06 ON public.products_cartitem USING btree (user_id);


--
-- Name: products_product_category_id_9b594869; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX products_product_category_id_9b594869 ON public.products_product USING btree (category_id);


--
-- Name: products_productfavorite_product_id_44bd0f0f; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX products_productfavorite_product_id_44bd0f0f ON public.products_productfavorite USING btree (product_id);


--
-- Name: products_productfavorite_user_id_536d560e; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX products_productfavorite_user_id_536d560e ON public.products_productfavorite USING btree (user_id);


--
-- Name: products_productreview_product_id_7e81c4a6; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX products_productreview_product_id_7e81c4a6 ON public.products_productreview USING btree (product_id);


--
-- Name: products_productreview_user_id_5c551aaa; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX products_productreview_user_id_5c551aaa ON public.products_productreview USING btree (user_id);


--
-- Name: products_productview_product_id_8f0dcfb8; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX products_productview_product_id_8f0dcfb8 ON public.products_productview USING btree (product_id);


--
-- Name: products_productview_user_id_6f19c8f7; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX products_productview_user_id_6f19c8f7 ON public.products_productview USING btree (user_id);


--
-- Name: products_recommendationlog_product_id_2ee7ab5e; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX products_recommendationlog_product_id_2ee7ab5e ON public.products_recommendationlog USING btree (product_id);


--
-- Name: products_recommendationlog_user_id_c502e077; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX products_recommendationlog_user_id_c502e077 ON public.products_recommendationlog USING btree (user_id);


--
-- Name: products_userbehavior_product_id_180e0599; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX products_userbehavior_product_id_180e0599 ON public.products_userbehavior USING btree (product_id);


--
-- Name: products_userbehavior_user_id_028b1105; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX products_userbehavior_user_id_028b1105 ON public.products_userbehavior USING btree (user_id);


--
-- Name: products_userproductrating_product_id_1989bb51; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX products_userproductrating_product_id_1989bb51 ON public.products_userproductrating USING btree (product_id);


--
-- Name: products_userproductrating_user_id_91b5b18f; Type: INDEX; Schema: public; Owner: ecommerce_user
--

CREATE INDEX products_userproductrating_user_id_91b5b18f ON public.products_userproductrating USING btree (user_id);


--
-- Name: accounts_userprofile_preferred_categories accounts_userprofile_productcategory_id_b2d7e7fa_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.accounts_userprofile_preferred_categories
    ADD CONSTRAINT accounts_userprofile_productcategory_id_b2d7e7fa_fk_products_ FOREIGN KEY (productcategory_id) REFERENCES public.products_productcategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_userprofile accounts_userprofile_user_id_92240672_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.accounts_userprofile
    ADD CONSTRAINT accounts_userprofile_user_id_92240672_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_userprofile_preferred_categories accounts_userprofile_userprofile_id_4f6c1827_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.accounts_userprofile_preferred_categories
    ADD CONSTRAINT accounts_userprofile_userprofile_id_4f6c1827_fk_accounts_ FOREIGN KEY (userprofile_id) REFERENCES public.accounts_userprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_cartitem products_cartitem_product_id_e735c06a_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_cartitem
    ADD CONSTRAINT products_cartitem_product_id_e735c06a_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_cartitem products_cartitem_user_id_c496ef06_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_cartitem
    ADD CONSTRAINT products_cartitem_user_id_c496ef06_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product products_product_category_id_9b594869_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_category_id_9b594869_fk_products_ FOREIGN KEY (category_id) REFERENCES public.products_productcategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_productfavorite products_productfavo_product_id_44bd0f0f_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_productfavorite
    ADD CONSTRAINT products_productfavo_product_id_44bd0f0f_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_productfavorite products_productfavorite_user_id_536d560e_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_productfavorite
    ADD CONSTRAINT products_productfavorite_user_id_536d560e_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_productreview products_productrevi_product_id_7e81c4a6_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_productreview
    ADD CONSTRAINT products_productrevi_product_id_7e81c4a6_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_productreview products_productreview_user_id_5c551aaa_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_productreview
    ADD CONSTRAINT products_productreview_user_id_5c551aaa_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_productview products_productview_product_id_8f0dcfb8_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_productview
    ADD CONSTRAINT products_productview_product_id_8f0dcfb8_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_productview products_productview_user_id_6f19c8f7_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_productview
    ADD CONSTRAINT products_productview_user_id_6f19c8f7_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_recommendationlog products_recommendat_product_id_2ee7ab5e_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_recommendationlog
    ADD CONSTRAINT products_recommendat_product_id_2ee7ab5e_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_recommendationlog products_recommendationlog_user_id_c502e077_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_recommendationlog
    ADD CONSTRAINT products_recommendationlog_user_id_c502e077_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_userbehavior products_userbehavio_product_id_180e0599_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_userbehavior
    ADD CONSTRAINT products_userbehavio_product_id_180e0599_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_userbehavior products_userbehavior_user_id_028b1105_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_userbehavior
    ADD CONSTRAINT products_userbehavior_user_id_028b1105_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_userproductrating products_userproduct_product_id_1989bb51_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_userproductrating
    ADD CONSTRAINT products_userproduct_product_id_1989bb51_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_userproductrating products_userproductrating_user_id_91b5b18f_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ecommerce_user
--

ALTER TABLE ONLY public.products_userproductrating
    ADD CONSTRAINT products_userproductrating_user_id_91b5b18f_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

