# Generated by Django 5.1.3 on 2024-11-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbehavior',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='review_score',
            field=models.FloatField(default=0),
        ),
    ]
